import './style.css';
import '@fontsource-variable/dm-sans';
import '@fontsource/dm-mono/400.css';
import { createIcons, ArrowUpRight, ArrowDown, Github, RotateCcw, Maximize2, Minimize2, Move, Rotate3d, ZoomIn, ZoomOut, Box, ChevronRight, X, ScanLine, Pause, Play } from 'lucide';

const figures = [
  { file:'vop-real-world.png', title:'Out of simulation. Into the crowd.', label:'01 / REAL-WORLD DEPLOYMENT', alt:'Unitree Go2 navigating people and static obstacles with a visualized velocity-obstacle field', desc:'Onboard perception meets a moving world. VOP-Nav is deployed on a Unitree Go2 in dynamic, crowded environments.' },
  { file:'vop-pipeline.png', title:'From perception to action.', label:'02 / SYSTEM ARCHITECTURE', alt:'VOP-Nav three-stage training pipeline and real-world deployment architecture', desc:'A three-stage pipeline connects a basic policy, VOP-Net training, and navigation-policy learning to real-world deployment.' },
  { file:'vop-velocity.png', title:'Finding room to move.', label:'03 / SAFE VELOCITY REGION', alt:'Safe velocity regions and velocity obstacles for a robot surrounded by moving obstacles', desc:'Velocity Obstacle geometry describes which velocities remain feasible as nearby obstacles move.' },
  { file:'vop-environments.png', title:'One policy. Different worlds.', label:'04 / SIMULATION ENVIRONMENTS', alt:'Forest, office, square, and slow training environments in simulation', desc:'Forest, office, square, and slow environments provide diverse conditions for training and evaluation.' },
];
const icon = (name, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
document.querySelector('#app').innerHTML = `
  <a class="skip-link" href="#playground">Skip to the robot</a>
  <div class="site-shell">
    <header class="site-header"><a href="#" class="wordmark" aria-label="Mkdm-Ele home">m<span class="wordmark-k">k</span>.<span class="wordmark-name">Mkdm-Ele</span></a><nav aria-label="Main navigation"><a href="#playground">Playground</a><a href="#research">Research</a><a href="https://github.com/Mkdm-Ele" target="_blank" rel="noopener noreferrer" class="nav-github">GitHub ${icon('arrow-up-right')}</a></nav></header>
    <main>
      <section class="intro" aria-labelledby="intro-title"><div class="intro-copy"><p class="eyebrow">PERCEPTION. LEARNING. ROBOTICS.</p><h1 id="intro-title">A little curiosity.<br>A world in motion<span class="accent-dot">.</span></h1><p class="bio">Hi, I'm <strong>Mkdm-Ele</strong> — a senior in Intelligent Sensing Engineering<br class="desktop-break"> at <strong>Shanghai Jiao Tong University.</strong></p></div><a class="identity-card" href="https://github.com/Mkdm-Ele" target="_blank" rel="noopener noreferrer" aria-label="Visit Mkdm-Ele on GitHub"><div class="avatar-well"><img src="/assets/avatar.jpg" alt="Mkdm-Ele's GitHub avatar: a plush character in a yellow duck costume" width="94" height="94"></div><div><span class="identity-name">Mkdm-Ele ${icon('arrow-up-right')}</span><span class="identity-sub">SJTU · Senior undergraduate</span></div></a></section>
      <section id="playground" class="playground" aria-labelledby="playground-title">
        <div class="section-label"><span><span class="section-number">01</span> THE PLAYGROUND</span><span class="quiet-label">A little closer to the real thing</span></div>
        <div class="robot-console">
          <div class="console-heading"><div><p class="eyebrow">UNITREE ROBOTICS</p><h2 id="playground-title">Meet Go2<span class="tiny-period">.</span></h2></div><span class="model-badge">${icon('box')} INTERACTIVE MODEL</span></div>
          <div id="robot-viewport" role="region" tabindex="0" aria-label="Interactive Go2 robot. Drag to orbit, scroll to zoom, right-drag to pan. Use arrow keys to orbit, plus or minus to zoom, and R to reset."><div class="viewer-loading" id="viewer-loading"><span class="loading-orbit"></span><span id="loading-label">Assembling Go2…</span></div><span class="stage-word" aria-hidden="true">go<span>2</span></span></div>
          <div class="stage-caption"><span class="live-status"><span id="model-dot"></span><span id="model-status" role="status">LOADING MODEL</span></span><span class="axis-label"><b>X</b> / <b>Y</b> / <b>Z</b></span></div>
          <div class="viewer-tools"><button class="round-button" id="zoom-in" aria-label="Zoom in" title="Zoom in">${icon('zoom-in')}</button><button class="round-button" id="zoom-out" aria-label="Zoom out" title="Zoom out">${icon('zoom-out')}</button><span class="tool-divider"></span><button class="round-button" id="reset-view" aria-label="Reset view" title="Reset view">${icon('rotate-ccw')}</button><button class="round-button" id="fullscreen" aria-label="Enter fullscreen" title="Fullscreen">${icon('maximize-2')}</button></div>
          <div class="console-bottom"><div class="pose-control" role="group" aria-label="Robot pose"><button class="pose-button active" data-pose="stand" aria-pressed="true">Stand</button><button class="pose-button" data-pose="crouch" aria-pressed="false">Crouch</button></div><div class="drag-hint">${icon('rotate-3d')} Drag to orbit <span>·</span> Scroll to zoom</div><button id="auto-rotate" class="auto-button" aria-pressed="false">${icon('play')} <span>Auto-rotate</span></button></div>
        </div>
        <div class="under-console"><span>12 articulated joints. Endless perspectives.</span><a href="#research">From movement to meaning ${icon('arrow-down')}</a></div>
      </section>
      <section id="research" class="research" aria-labelledby="research-title"><div class="section-label"><span><span class="section-number">02</span> SELECTED WORK</span><span class="quiet-label">Learning to navigate the world</span></div><article class="research-card"><div class="research-heading"><div><div class="research-kicker"><span class="research-category">LEGGED NAVIGATION</span><span class="research-year">2026</span></div><h2 id="research-title">VOP-Nav<span class="accent-dot">.</span></h2><p class="paper-title">Learning Agile Navigation in Crowded<br class="desktop-break"> Environments for Quadruped Robots</p></div><a class="paper-link" href="https://arxiv.org/abs/2607.15036" target="_blank" rel="noopener noreferrer">Read the paper ${icon('arrow-up-right')}</a></div><p class="research-summary">Helping quadruped robots find their way through a moving crowd. VOP-Nav brings velocity obstacle perception and reinforcement learning together — turning onboard observations into agile, collision-aware motion.</p><div class="research-tags"><span>Velocity obstacle perception</span><span>Reinforcement learning</span><span>Sim-to-real</span></div><div class="figure-gallery"><button class="figure-main" id="figure-open" aria-label="Enlarge research image"><img id="figure-image" src="/assets/${figures[0].file}" alt="${figures[0].alt}" loading="lazy"><span class="enlarge-hint">${icon('maximize-2')} Explore figure</span></button><div class="figure-caption"><div><p class="eyebrow" id="figure-label">${figures[0].label}</p><h3 id="figure-title">${figures[0].title}</h3></div><span id="figure-count">01 <span>/ 04</span></span></div><p id="figure-description">${figures[0].desc}</p><div class="figure-tabs" role="group" aria-label="Research figures">${figures.map((f,i)=>`<button class="figure-tab ${i===0?'active':''}" data-figure="${i}" aria-pressed="${i===0}"><span class="thumbnail"><img src="/assets/${f.file}" alt="" loading="lazy"></span><span><small>0${i+1}</small>${['In the real world','The pipeline','Safe velocities','Training worlds'][i]}</span></button>`).join('')}</div></div><div class="research-footer"><span>Perception → prediction → action</span><a href="https://mp.weixin.qq.com/s/MJ0KtTtTbK9Lg5eA-efciw" target="_blank" rel="noopener noreferrer">Read the story ${icon('arrow-up-right')}</a></div></article></section>
    </main><footer class="site-footer"><span>Mkdm-Ele <span class="footer-slash">/</span> A work in motion.</span><a href="https://github.com/Mkdm-Ele" target="_blank" rel="noopener noreferrer">${icon('github')} Find me on GitHub ${icon('arrow-up-right')}</a><span class="footer-location">Shanghai, China</span></footer>
  </div><dialog id="figure-dialog" aria-label="Research figure viewer"><div class="dialog-top"><span id="dialog-caption"></span><button id="close-dialog" class="round-button" aria-label="Close image">${icon('x')}</button></div><img id="dialog-image" alt=""><div class="dialog-nav"><button id="previous-figure">← Previous</button><span id="dialog-count"></span><button id="next-figure">Next →</button></div></dialog>`;
const icons={ArrowUpRight,ArrowDown,Github,RotateCcw,Maximize2,Minimize2,Move,Rotate3d,ZoomIn,ZoomOut,Box,ChevronRight,X,ScanLine,Pause,Play};
export const refreshIcons=()=>createIcons({icons,attrs:{'stroke-width':1.65}});
refreshIcons();
let selected=0;
const dialog=document.querySelector('#figure-dialog');
function selectFigure(index){selected=(index+figures.length)%figures.length;const f=figures[selected];document.querySelector('#figure-image').src='/assets/'+f.file;document.querySelector('#figure-image').alt=f.alt;document.querySelector('#figure-label').textContent=f.label;document.querySelector('#figure-title').textContent=f.title;document.querySelector('#figure-description').textContent=f.desc;document.querySelector('#figure-count').innerHTML=`0${selected+1} <span>/ 04</span>`;document.querySelectorAll('.figure-tab').forEach((b,i)=>{b.classList.toggle('active',i===selected);b.setAttribute('aria-pressed',String(i===selected));});document.querySelector('#dialog-image').src='/assets/'+f.file;document.querySelector('#dialog-image').alt=f.alt;document.querySelector('#dialog-caption').textContent=f.label;document.querySelector('#dialog-count').textContent=`${selected+1} / ${figures.length}`;}
document.querySelectorAll('[data-figure]').forEach(b=>b.addEventListener('click',()=>selectFigure(Number(b.dataset.figure))));
document.querySelector('#figure-open').addEventListener('click',()=>{selectFigure(selected);dialog.showModal();});
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
document.querySelector('#previous-figure').addEventListener('click',()=>selectFigure(selected-1));
document.querySelector('#next-figure').addEventListener('click',()=>selectFigure(selected+1));
dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')selectFigure(selected-1);if(e.key==='ArrowRight')selectFigure(selected+1);});
import('./robot.js').then(m=>m.initRobot()).catch(error=>{console.error(error);document.querySelector('#loading-label').textContent='The 3D viewer could not start. Please reload in a WebGL-enabled browser.';document.querySelector('#model-status').textContent='VIEWER UNAVAILABLE';});
